- id: '1744525381749'
  alias: getHyponToken
  description: ''
  triggers:
  - trigger: time_pattern
    hours: /1
  conditions:
  - condition: sun
    before: sunset
    after: sunrise
  actions:
  - action: shell_command.get_hypontoken
    metadata: {}
    data: {}
    response_variable: service.hyponToken
  mode: single
- id: '1744526990277'
  alias: getHyponData
  description: ''
  triggers:
  - trigger: time_pattern
    minutes: /4
  conditions:
  - condition: sun
    before: sunset
    after: sunrise
    after_offset: +00:04:00
    before_offset: -00:20:00
  actions:
  - action: shell_command.get_hypondata
    metadata: {}
    data: {}
  mode: single
- id: '1744632020424'
  alias: setHyponCloseDay
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: +00:30:00
  conditions: []
  actions:
  - action: shell_command.set_hyponclose
    metadata: {}
    data: {}
  mode: single